services:
  postgresdb_healtshoper:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
#      no_proxy: localhost,127.0.0.1
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - health_shoper_network
        
  seq_healtshoper:
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=${SEQ_FIRSTRUN_ADMINUSERNAME}
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    volumes:
      - seq_data_healtshoper:/data
    networks:
      - health_shoper_network
        
  
  pgadmin_healtshoper:
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - health_shoper_network